### ISSUE TITLE
Move Grafana to new machine

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/maintenance#21]
Move Grafana to Danswer machine

1. List the configuration files which need to be copied over
2. List any databases / data on the local grafana machine which need to be copied over
3. Copy all resources over
4. Open relevant port
5. Create new EC2 Target
6. Update EC2 LB rule to point to new target
7. Verify setup
8. Shut down old Grafana machine
9. Terminate and delete volume after 15 days

**Comment by Ishankoradia** [comment]
Grafana and prometheus are on the same machine. 

Prometheus - is a open source monitoring toolkit that gathers data (metrics) from multiple sources. It is very good at handling time series data. For migrating prometheus to another machine follow these steps

1. Install prometheus with the correct user (& permissions) according to the instructions here

<img width="768" alt="Screenshot 2024-07-10 at 11 27 26" src="https://github.com/DalgoT4D/maintenance/assets/39583356/1ed6824f-e0b6-45e7-b142-19574e3410fe">

2. Copy `/etc/prometheus/prometheus.yml` and `/etc/systemd/system/prometheus.service` from the old machine to the new

3. Copy the localdb (the timeseries db) at `/var/lib/prometheus` from the old machine to the new. Use `rsync` to sync the databases so we copy incrementally. https://www.digitalocean.com/community/tutorials/how-to-use-rsync-to-sync-local-and-remote-directories

4. Start and enable the prometheus service to start on boot. If everything is in order , prometheuse server will be running on `[localhost](http://localhost:9090)`

**Comment by fatchat** [comment]
does the prod machine push metrics to this new machine or will the new machine pull from prod

firewalls and dns also need to be updated (which i will do)

**Comment by Ishankoradia** [comment]
Prometheus pull metrics from the targets (via http enddpoints). So the new machien will pull from prod.

Yes relevant firewalls/dns will need to be updated.

**Comment by Ishankoradia** [comment]
Install the `postgres exporter`
<img width="716" alt="Screenshot 2024-07-15 at 06 10 09" src="https://github.com/user-attachments/assets/1736f42e-ac4e-42d5-9362-c2f580cb8d93">

**Comment by Ishankoradia** [comment]
Node exporter version

<img width="899" alt="Screenshot 2024-08-05 at 08 40 37" src="https://github.com/user-attachments/assets/48430236-fd70-470f-a7d4-11729fad4839">
