### ISSUE TITLE
Move Vaultwarden to everything machine

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/maintenance#22]
Move Grafana to Danswer machine

1. List the configuration files which need to be copied over
2. List any databases / docker volumes / other data on the local vaultwarden machine which need to be copied over
3. Copy all resources over
4. Open relevant port
5. Create new EC2 Target
6. Update EC2 LB rule to point to new target
7. Verify setup
8. Shut down old Vaultwarden machine
9. Terminate and delete volume after 15 days

**Comment by Ishankoradia** [comment]
@fatchat can we close this
