### ISSUE TITLE
Plan the next Airbyte upgrade

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/maintenance#28]
Step 1: Look at Airbyte's releases and recommend a version to upgrade to

Step 2: Once the target version is agreed upon, list all changes which would break our integration

Step 3: Make a plan to address those changes

**Comment by Ishankoradia** [comment]
https://airbytehq.slack.com/archives/C01AHCD885S/p1723584049729239?thread_ts=1721655918.685019&cid=C01AHCD885S

@mdshamoon maybe take a look at this, for the next upgrade. 

One of their developers, recommends using `abctl` (airbyte command line tool) to install/manage airbyte locally.

**Comment by mdshamoon** [comment]
https://docs.google.com/document/d/1GRmT5MtB3Ds0QXLrfMr45_IFsZ4R_vhyMvXiRJYW7bI/edit

**Comment by Ishankoradia** [comment]
<img width="553" alt="Screenshot 2024-08-24 at 21 55 25" src="https://github.com/user-attachments/assets/5bb6ed7b-20e9-4f7d-9a3d-3de11d2dbd7f">

**Comment by fatchat** [comment]
i knew `run-ab-platform` was deprecated but i thought they still ran on Docker

urgh

**Comment by Ishankoradia** [comment]
Its time we get into `kubernetes` for our production setup also.

**Comment by fatchat** [comment]
Created machine `airbyte-upgrade` and RDS `airbyte-upgrade`
Installed Airbyte 0.50.44
Got it running

**Comment by Ishankoradia** [comment]
Let me know once you test the docker `prefect-proxy` while setting up Dalgo here. 

But how will you test the case where deployments are already there and we shift to a docker setup ?

**Comment by fatchat** [comment]
Good point I'm not testing that... I'm only testing Airbyte, the docker setup for Dalgo is just to save myself some time

**Comment by fatchat** [comment]
Dalgo is set up
`org1` with a Postgres warehouse
syncs are running

**Comment by fatchat** [comment]
`org2` with a BigQuery warehouse, syncs are running

**Comment by fatchat** [comment]
before upgrading Airbyte
- creating a snapshot of the volume 
- creating a backup of the airbyte RDS

**Comment by fatchat** [comment]
`abctl` requires Go

Following https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-20-04

`curl -OL https://golang.org/dl/go1.23.0.linux-amd64.tar.gz`

`sudo tar -C /usr/local -xvf go1.23.0.linux-amd64.tar.gz`

**Comment by fatchat** [comment]
20 GB storage wasn't enough for the next step so I upgraded the volume to 40 GB before running

`go install github.com/airbytehq/abctl@latest`

`abctl` has the following usage for installations

```
ubuntu@ip-172-31-21-134:~$ abctl local install --help
Install Airbyte locally

Usage:
  abctl local install [flags]

Flags:
      --chart-version string     specify the Airbyte helm chart version to install (default "latest")
      --docker-email string      docker email, can also be specified via ABCTL_LOCAL_INSTALL_DOCKER_EMAIL
      --docker-password string   docker password, can also be specified via ABCTL_LOCAL_INSTALL_DOCKER_PASSWORD
      --docker-server string     docker registry, can also be specified via ABCTL_LOCAL_INSTALL_DOCKER_SERVER (default "https://index.docker.io/v1/")
      --docker-username string   docker username, can also be specified via ABCTL_LOCAL_INSTALL_DOCKER_EMAIL
  -h, --help                     help for install
      --host string              ingress http host (default "localhost")
      --insecure-cookies         allow insecure cookies to be served over http
      --low-resource-mode        run Airbyte in low resource mode
      --migrate                  migrate data from docker compose installation
      --no-browser               disable launching the web-browser post install
      --port int                 ingress http port (default 8000)
      --secret strings           an Airbyte helm chart secret file
      --values string            the Airbyte helm chart values file to load
      --volume strings           additional volume mounts (format: <HOST_PATH>:<GUEST_PATH>)
```

The documentation for `--migrate` says 

```
Enables data-migration from an existing docker-compose backed Airbyte installation.

Copies, leaving the original data unmodified, the data from a docker-compose backed Airbyte installation into this abctl managed Airbyte installation.
```

**Comment by fatchat** [comment]
```
ubuntu@ip-172-31-21-134:~$ abctl local status
  INFO    Thanks for using Airbyte!
          Anonymous usage reporting is currently enabled. For more information, please see https://docs.airbyte.com/telemetry
  INFO    Using Kubernetes provider:
            Provider: kind
            Kubeconfig: /home/ubuntu/.airbyte/abctl/abctl.kubeconfig
            Context: kind-airbyte-abctl
 SUCCESS  Found Docker installation: version 27.2.0
 WARNING  Airbyte does not appear to be installed locally
 ▄ Checking for existing Kubernetes cluster 'airbyte-abctl' 
```

(the check on the last line had no output)

**Comment by fatchat** [comment]
It looks like we need to move to Kubernetes before upgrading

**Comment by fatchat** [comment]
`kapa.ai` says we can upgrade before moving to kubernetes or to `abctl`. will attempt that now

**Comment by fatchat** [comment]
Error:
```
Error response from daemon: create /tmp/airbyte_local: "/tmp/airbyte_local" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

Removed volume `docker volume rm airbyte_workspace`

Airbyte started successfully but the logs were gone

Dalgo started and the dashboard opened
- source details were available

**Comment by fatchat** [comment]
Source Connectors to check

- [ ] SurveyCTO `tech4dev/source-surveycto:0.1.1`
- [ ] Commcare `tech4dev/source-commcare:0.1.0`
- [ ] Commcare `tech4dev/source-commcare:0.2.0`
- [ ] Kobo Toolbox `tech4dev/source-kobotoolbox:0.2.0`
- [ ] Kobo Toolbox `tech4dev/source-kobotoolbox:0.2.1`
- [ ] Glific
- [ ] Avni
- [ ] Frappe (INREM)
- [ ] mGramSeva {Arghyam)
- [ ] Salesforce (Antarang)
- [ ] Postgres (Noora) `airbyte/source-postgres:2.0.33`
- [ ] Freshdesk (Noora)

**Comment by fatchat** [comment]
APIs to check

- [ ] "workspaces/list"
- [ ] "workspaces/get"
- [ ] "workspaces/update_name"
- [ ] "workspaces/create"
- [ ] "workspaces/delete"
- [ ] "source_definitions/get_for_workspace"
- [ ] "source_definition_specifications/get"
- [ ] "source_definitions/create_custom"
- [ ] "source_definitions/list_for_workspace"
- [ ] "sources/list"
- [ ] "sources/get"
- [ ] "sources/delete"
- [ ] "source_definition_specifications/get"
- [ ] "sources/create"
- [ ] "sources/update"
- [ ] "source_definition_specifications/get"
- [ ] "scheduler/sources/check_connection"
- [ ] "sources/check_connection_for_update"
- [ ] "sources/discover_schema"
- [ ] "destination_definitions/list_for_workspace"
- [ ] "destination_definitions/get"
- [ ] "destination_definition_specifications/get"
- [ ] "destinations/list"
- [ ] "destinations/get"
- [ ] "destinations/delete"
- [ ] "destinations/create"
- [ ] "destinations/update"
- [ ] "scheduler/destinations/check_connection"
- [ ] "destinations/check_connection_for_update"
- [ ] "connections/list"
- [ ] "web_backend/connections/list"
- [ ] "web_backend/connections/get"
- [ ] "connections/create"
- [ ] "connections/update"
- [ ] "connections/reset"
- [ ] "connections/delete"
- [ ] "connections/sync"
- [ ] "jobs/get_debug_info"
- [ ] "jobs/list"
- [ ] "attempt/get_for_job"
- [ ] "web_backend/connections/get"
- [ ] "web_backend/connections/update"

**Comment by Ishankoradia** [comment]
Looks like google server issue.

**Comment by Ishankoradia** [comment]
### Schema change testing

## Google sheets

- version - 0.3.13
- source had two streams `sheet2` & `sheet22`
- tested following schema changes using Dalgo UI. click on `refresh source schema` and then accepted changes via `Pending Actions`
     - remove a column  `sheet2`
     - added a new column `sheet2`
     - both cases did a reset (of only `sheet2`) + sync after accepting the schema changes

**Comment by fatchat** [comment]
## Freshdesk
[x] Sync ran

**Comment by Ishankoradia** [comment]
## Salesforce
- [x] Sync ran. I had to stop in the middle since the no of rows were too big and antarang's pipeline was scheduled.
