### ISSUE TITLE
monitor everything machine with grafana

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/maintenance#31]
infra metrics from prometheus

@Ishankoradia can you guide himanshu through this please

**Comment by fatchat** [comment]
https://jayanthkumar777.hashnode.dev/comprehensive-guide-to-monitoring-infrastructure-databases-django-app-metrics-with-grafana-and-prometheus

**Comment by himanshudube97** [comment]
@fatchat 
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/cea6e6e2-737e-4233-a92b-94860df5d314">

**Current setup-> One instance of Prometheus and Grafana on everything machine and Multiple node-exporter instances.**
- Prometheus is running on the EVERYTHING machine and collects machine-related data.
- Grafana is also running on the EVERYTHING machine and uses data from Prometheus to create dashboards.
- Node-exporter runs on different machines that we want to monitor, generating the machine-specific metrics.

**Prometheus pulls (or scrapes) the data from Node Exporter.**

**How to setup the grafana dashboard for future machines->**

1. Install Node Exporter on the machine you want to monitor.
2. Ensure Node Exporter is running and accessible on port 9100
3. Configure the prometheus.yml file on the EVERYTHING machine.
4. Add the IP address of the new machine under the _scrape_configs_ section with the port Node Exporter is running on.
<node_exporter_machine_ip>:9100 
5. Save and restart Prometheus.
6. Go to https://grafana.projecttech4dev.org/    OR  localhost:3000/ there you will see a list of node-exporter ips under the Host dropdown. Select the one which you want to monitor.
